version: '3.8'

services:
  
  frontend:
    image: ninadrathod/meverse-frontend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meverse-frontend
    ports:
      - "3000:3000" #Expose 3000 in container as 3000 on host
    volumes:
      - .:/app
      - /app/node_modules